import os
import argparse
import re

# Parse command line argument for the file name
parser = argparse.ArgumentParser(description="Create a new article HTML file and update articles.html.")
parser.add_argument('file_name', help="The name of the HTML file to be created.")
args = parser.parse_args()

# Create a new HTML file in the articles directory
new_file_path = os.path.join('articles', f'{args.file_name}.html')

default_html_content = f"""
<!DOCTYPE html>
<html lang="en-AU">
    <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0'>
        <link rel="apple-touch-icon" sizes="180x180" href="https://pendulumpsychology.com.au/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="https://pendulumpsychology.com.au/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="https://pendulumpsychology.com.au/favicon-16x16.png">
        <link rel="manifest" href="https://pendulumpsychology.com.au/site.webmanifest">
        <link rel="mask-icon" href="https://pendulumpsychology.com.au/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Maven+Pro">
        <link rel="stylesheet" href="https://pendulumpsychology.com.au/style.css">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <title>TODO | Pendulum Psychology</title>
        <meta name="description" content="TODO"/>
        <meta name="robots" content="index, follow">
        <link rel="canonical" href="https://pendulumpsychology.com.au/articles/{args.file_name}.html">
        <link rel="alternate" href="https://pendulumpsychology.com.au/articles/{args.file_name}.html" hreflang="en-AU">
        <meta charset="utf-8"/>
        <meta property="og:locale" content="en_AU">
        <meta property="og:title" content="TODO | Pendulum Psychology" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://pendulumpsychology.com.au/articles/{args.file_name}.html" />
        <meta property="og:image" content="https://pendulumpsychology.com.au/android-chrome-512x512.png" />
        <meta property="og:description" content="TODO">
        <meta property="og:site_name" content="TODO | Pendulum Psychology">
        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {{
              "@context": "https://schema.org",
              "@type": "Article",
              "mainEntityOfPage": {{
                "@type": "WebPage",
                "@id": "https://pendulumpsychology.com.au/articles/{args.file_name}.html"
              }},
              "headline": "TODO",
              "image": "https://pendulumpsychology.com.au/android-chrome-512x512.png",  
              "author": {{
                "@type": "Person",
                "name": "David O'Donohue"
              }},
              "publisher": {{
                "@type": "Organization",
                "name": "Pendulum Psychology",
                "logo": {{
                  "@type": "ImageObject",
                  "url": "https://pendulumpsychology.com.au/android-chrome-512x512.png"
                }}
              }},
              "datePublished": "TODO",
              "description": "TODO"
            }}
            </script>
    </head>
    <body>
        <!-- START_NAVBAR -->
        <!-- END_NAVBAR -->
        <main>
        <section>
        <h1>TODO: Title</h1>
        <br><br>
        <p class="italics">Last updated TODO: date</p>
        <br><br>
        <p class="italics">Share this article via:</p>
        <br>
        <!-- Facebook -->
      
<a href="https://www.facebook.com/sharer/sharer.php?u=https://pendulumpsychology.com.au/articles/{args.file_name}.html" class="share-button" target="_blank">
  <img src="https://pendulumpsychology.com.au/assets/icons/facebook.svg" alt="Facebook" style="width:32px;height:32px;border:0;">
</a>
<!-- Twitter -->
<a href="https://twitter.com/share?url=https://pendulumpsychology.com.au/articles/{args.file_name}.html&text=TODO:Text" class="share-button" target="_blank">
  <img src="https://pendulumpsychology.com.au/assets/icons/twitter.svg" alt="Twitter" style="width:32px;height:32px;border:0;">
</a>
<!-- LinkedIn -->
<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://pendulumpsychology.com.au/articles/{args.file_name}.html&title=TODO:Text" class="share-button" target="_blank">
  <img src="https://pendulumpsychology.com.au/assets/icons/linkedin.svg" alt="LinkedIn" style="width:32px;height:32px;border:0;">
</a>
<!-- WhatsApp -->
<a href="whatsapp://send?text=https://pendulumpsychology.com.au/articles/{args.file_name}.html" data-action="share/whatsapp/share" class="share-button" target="_blank">
  <img src="https://pendulumpsychology.com.au/assets/icons/whatsapp.svg" alt="WhatsApp" style="width:32px;height:32px;border:0;">
</a>
<!-- Email -->
<a href="mailto:?subject=I wanted to share this with you&body=https://pendulumpsychology.com.au/articles/{args.file_name}.html" class="share-button">
  <img src="https://pendulumpsychology.com.au/assets/icons/email.svg" alt="Email" style="width:32px;height:32px;border:0;">
</a>
        <p>
          <br><br>
          CONTENT
            </p>
        </section>
        </main>
        <!-- START_FOOTER -->
        <!-- END_FOOTER -->
        <script src="https://pendulumpsychology.com.au/script.js"></script>
    </body>
</html>
"""

with open(new_file_path, 'w') as file:
    file.write(default_html_content)

# Update articles.html in the current directory
with open('articles.html', 'r+') as file:
    content = file.read()
    position = content.find('<!-- MORE_ARTICLES -->')

    if position != -1:
        new_content = f'''
        <div class="card">
            <img src="TODO" alt="TODO" class="card-img">
            <h2 class="card-title">TODO: Title</h2>
            <p class="card-desc">In development.</p>
            <a href="https://pendulumpsychology.com.au/articles/{args.file_name}.html" class="card-btn">Read More</a>
        </div>
        <!-- MORE_ARTICLES -->'''

        content = content[:position] + new_content + content[position+len('<!-- MORE_ARTICLES -->'):]

    file.seek(0)
    file.write(content)
    file.truncate()
